name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyse-et-tests:
    name: Analyse statique et tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Récupérer les dépendances
        run: flutter pub get

      - name: Analyse statique
        run: flutter analyze

      - name: Tests
        run: flutter test
